#! /usr/bin/env python

import unittest
import rospy
import rostest
from std_msgs.msg import String


class TestHostName(unittest.TestCase):

    def __init__(self, *args):
        unittest.TestCase.__init__(self, *args)

        rospy.init_node('test')

        self.hostname = rospy.get_param("hostname")

        topic = rospy.get_param("hosts_topic")
        self.correct_hostname = True
        self. sub = rospy.Subscriber(topic, String, self.cb, queue_size=10)

    def cb(self, msg: String) -> None:
        if msg.data != self.hostname:
            self.correct_hostname = False

    def test_value(self):
        time_end = rospy.Time.now() + rospy.Duration.from_sec(2)
        while rospy.Time.now() < time_end and self.correct_hostname and not rospy.is_shutdown():
            rospy.sleep(0.1)
        if rospy.is_shutdown():
            self.fail("shutdown")

        self.failUnless(self.correct_hostname, "An incorrect hostname has been published")


if __name__ == '__main__':
    rostest.rosrun('rgbd', "hostname_sub_value_test", TestHostName)
